"""
CLI renderer for maze visualization.

This module provides terminal-based rendering for mazes generated by
MazeGenerator. It converts a bitmask-based grid into a Unicode/ASCII
maze using box-drawing characters and ANSI colors.

Features include:
    - CLI rendering of maze walls and structure
    - Start/goal and shortest path visualization
    - Day/night theme support
    - Simple animation during generation

This module is strictly responsible for presentation logic and does
not handle maze generation or solving.
"""

import time
from typing import Any

# Box Drawing Characters
V_WALL = "┃"
H_WALL = "━━━"
RESET = "\033[0m"  # Resets all ANSI formatting

wall_colors_rotation = [
    "\033[38;5;240m",  # Dark gray
    "\033[38;5;67m",   # Medium blue
    "\033[38;5;108m",  # Soft green
    "\033[38;5;137m",  # Brown
    "\033[38;5;131m"   # Muted red
]

north, east, south, west = 1, 2, 4, 8

THEMES = {
    "day": {
        "start": "\033[38;5;78m",    # Bright green
        "goal": "\033[38;5;203m",    # Pink
        "path": "\033[38;5;222m",    # Light beige
        "pattern": "\033[48;5;230m"  # Light cream
    },
    "night": {
        "start": "\033[38;5;117m",   # Light sky blue
        "goal": "\033[38;5;215m",    # Soft orange
        "path": "\033[38;5;246m",    # Medium gray
        "pattern": "\033[48;5;236m"  # Dark gray-blue
    }
}


class RenderError(Exception):
    """Exception raised when maze rendering fails.

    Used when:
    - unable to retrieve maze data
    - maze format is invalid or missing
    """
    pass


class CLIRenderer:
    """
    Renderer class to display the maze in a CLI.

    This class acts as a bridge between the reusable `MazeGenerator`
    module and the application-specific rendering logic.

    Attributes:
        grid (list[list[int]]): The maze grid bitmask.
        entry (tuple[int, int]): Coordinates of the start of the maze.
        exit (tuple[int, int]): Coordinates of the end of the maze.
        width (int): Width of the maze.
        height (int): Height of the maze.
        mode (str): Display theme mode, either 'day' or 'night'.
        wall_color (str): Current ANSI color code for rendering walls.
        color_index (int): Index of the current wall color
            in the rotation sequence.
        path (str): String representation of the path from entry to exit.
    """
    def __init__(self, maze_info: dict[str, Any]) -> None:
        """
        Initializes the CLIRenderer.

        Args:
            maze_info (dict[str, Any]): Dictionary containing maze
                configuration including 'grid', 'entry', 'exit',
                'width', and 'height'.

        Raises:
            RenderError: If `maze_info` is not a dict or
                if any required key is missing.
        """
        if not isinstance(maze_info, dict):
            raise RenderError("maze_info must be a dict")
        try:
            self.grid = maze_info["grid"]
            self.entry = maze_info["entry"]
            self.exit = maze_info["exit"]
            self.width = maze_info["width"]
            self.height = maze_info["height"]
        except KeyError as e:
            raise RenderError("Unable to retrieve maze_info. "
                              f"Missing key: {e}")

        self.mode = "day"
        self.wall_color = "\033[38;5;240m"
        self.color_index = 0
        self.path: str = ""
        self.pattern_error: str | None = None

    def toggle_mode(self) -> None:
        """
        Toggles the display theme mode between 'day' and 'night'.

        Returns:
            None
        """
        self.mode = "night" if self.mode == "day" else "day"

    def rotate_wall_color(self) -> str:
        """
        Rotates the wall color to the next one
        in the predefined rotation list.

        Returns:
            str: The ANSI color code for the next wall color.
        """
        self.color_index = (self.color_index + 1) % len(wall_colors_rotation)
        self.wall_color = wall_colors_rotation[self.color_index]
        return self.wall_color

    def render_maze(self, show_path: bool, final: bool,
                    color: str | None = None) -> str:
        """
        Renders the maze grid into a string representation.

        This function converts the bitmask grid into an ASCII/Unicode maze
        and optionally overlays the shortest path.

        Args:
            show_path (bool): Whether to display the shortest path.
            final (bool): Whether this is the final render
                (shows start/goal/42 pattern).

        Returns:
            str: Fully rendered maze as a string.

        Raises:
            RenderError: If the maze grid is empty or invalid.
        """
        grid = self.grid
        entry = self.entry
        exit = self.exit
        width = self.width
        height = self.height
        path_line = self.path

        if not grid:
            raise RenderError("Maze is invalid.")

        path_cells = set()
        path_cells = self._build_path_cells(entry, path_line)

        theme = THEMES.get(self.mode, THEMES["day"])
        wall_color = color if color is not None else self.wall_color

        output = []
        for y in range(height + 1):
            line = ""
            for x in range(width + 1):
                corners = self._get_corner(grid, x, y, width, height)
                line += f"{wall_color}{corners}{RESET}"

                if x < width:
                    if y == 0:
                        has_h = grid[0][x] & north
                    elif y == height:
                        has_h = grid[height - 1][x] & south
                    else:
                        has_h = ((grid[y - 1][x] & south)
                                 or (grid[y][x] & north))

                    line += f"{wall_color}{H_WALL}{RESET}" if has_h else "   "
            output.append(line)

            if y < height:
                line = ""
                for x in range(width + 1):
                    if x == 0:
                        has_v = grid[y][0] & west
                    elif x == width:
                        has_v = grid[y][width - 1] & east
                    else:
                        has_v = (grid[y][x - 1] & east) or (grid[y][x] & west)

                    line += f"{wall_color}{V_WALL}{RESET}" if has_v else " "

                    if x < width:
                        if (x, y) == entry and final:
                            line += f" \033[1m{theme['start']}S{RESET} "
                        elif (x, y) == exit and final:
                            line += f" \033[1m{theme['goal']}G{RESET} "
                        elif (x, y) in path_cells:
                            if show_path:
                                line += f" {theme['path']}·{RESET} "
                            else:
                                line += f"  {RESET} "
                        elif grid[y][x] == 15 and final:
                            line += f"{theme['pattern']}   {RESET}"
                        else:
                            line += "   "
                output.append(line)

        return ("\n".join(output))

    def pre_render(self, color: str | None = None) -> None:
        """
        Renders an intermediate frame of the maze during generation.

        This method is typically called repeatedly by the maze generator
        to visualize the step-by-step maze generation process.

        Returns:
            None
        """
        self.display_maze(show_path=False, final=False, color=color)
        time.sleep(0.03)

    def display_maze(
            self,
            show_path: bool = True,
            final: bool = True,
            clear_screen: bool = True,
            color : str | None = None
    ) -> None:
        """
        Prints the rendered maze to the terminal.

        Args:
            show_path (bool, optional): Whether to overlay the
                shortest path on the maze. Defaults to True.
            final (bool, optional): Indicates whether this is the
                final render (affects whether some ui elements
                are displayed). Defaults to True.
            clear_screen (bool, optional): Whether to clear the
                terminal screen before rendering. Defaults to True.

        Returns:
            None
        """
        if clear_screen:
            print("\033[H\033[J", end="")
        print(self.render_maze(show_path=show_path, final=final, color=color))
        if self.pattern_error:
            print(self.pattern_error)

    def _get_corner(
            self,
            grid: list[list[int]],
            x: int,
            y: int,
            width: int,
            height: int
    ) -> str:
        """
        Computes the Unicode box-drawing character for a corner junction.

        Args:
            grid (list[list[int]]): Maze grid encoded with bitmask walls.
            x (int): X-coordinate of the corner.
            y (int): Y-coordinate of the corner.
            width (int): Maze width.
            height (int): Maze height.

        Returns:
            str: Unicode character representing the wall junction.
        """
        # Checks corners of cell (x, y)
        nw = grid[y - 1][x - 1] if y > 0 and x > 0 else 0
        ne = grid[y - 1][x] if y > 0 and x < width else 0
        sw = grid[y][x - 1] if y < height and x > 0 else 0
        se = grid[y][x] if y < height and x < width else 0

        # Wall exists if statement resolves to TRUE
        up = bool((nw & east) or (ne & west))  # East of nw or West of ne
        down = bool((sw & east) or (se & west))  # East of sw or West of se
        # South of nw or North of sw
        left = bool((nw & south) or (sw & north))
        # South of ne or North of se
        right = bool((ne & south) or (se & north))

        # Checks up, down, left, right walls
        # and picks the corresponding symbol
        res = {
            (True, True, True, True): "╋",
            (True, True, True, False): "┫",
            (True, True, False, True): "┣",
            (True, True, False, False): "┃",
            (True, False, True, True): "┻",
            (True, False, True, False): "┛",
            (True, False, False, True): "┗",
            (True, False, False, False): "┃",
            (False, True, True, True): "┳",
            (False, True, True, False): "┓",
            (False, True, False, True): "┏",
            (False, True, False, False): "┃",
            (False, False, True, True): "━",
            (False, False, True, False): "━",
            (False, False, False, True): "━",
            (False, False, False, False): " "
        }
        return res.get((up, down, left, right), " ")

    def _build_path_cells(
            self,
            start: tuple[int, int],
            path_str: str
    ) -> set[tuple[int, int]]:
        """
        Converts a path string into a set of coordinates along the path.

        Args:
            start (tuple[int, int]): Starting coordinate.
            path_str (str): Path encoded as directions (N, E, S, W).

        Returns:
            set[tuple[int, int]]: Set of coordinates visited along the path.
        """
        x, y = start
        cells = {(x, y)}
        moves = {"N": (0, -1), "E": (1, 0), "S": (0, 1), "W": (-1, 0)}

        for step in path_str:
            dx, dy = moves.get(step, (0, 0))
            x += dx
            y += dy
            cells.add((x, y))

        return cells
